import { MattressListing, NotificationItem } from "../types";

export const DEFAULT_LISTINGS: MattressListing[] = [
  {
    id: "simmons-black-hz",
    title: "Simmons Beautyrest Black L-Class, King Size",
    brand: "Simmons",
    price: 4500,
    retailPrice: 28000,
    size: "1.8m",
    dimensionsText: "1.8m x 2.0m",
    material: "Spring",
    thicknessCm: 32,
    useDuration: "1.5 years",
    condition: "Like New",
    hygieneNote:
      "Professionally sanitized, always paired with custom fitted protector. No children or pets in the household.",
    hasElevator: true,
    deliveryOption: "Pick-up Only",
    description:
      "Selling this gorgeous Simmons Beautyrest Black L-Class mattress. Experience ultimate luxury and pristine sleep quality. Relocating to Singapore next month and must part with it. Extremely clean condition, effectively like new. Zero stains, zero dips. Pocket springs provide excellent localized contouring support.",
    city: "Hangzhou",
    district: "Binjiang District",
    distanceKm: 2.1,
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: true,
    isHygieneVerified: true,
    isCleaned: true,
    wechatId: "sim_beauty_hz",
    phone: "138-8888-9999",
    createdAt: "2026-06-01",
  },
  {
    id: "tempur-proadapt-hz",
    title: "Tempur-Pedic ProAdapt Medium, Queen",
    brand: "Tempur-Pedic",
    price: 3200,
    retailPrice: 12000,
    size: "1.5m",
    dimensionsText: "1.5m x 2.0m",
    material: "Memory Foam",
    thicknessCm: 30,
    useDuration: "Under 1 Year",
    condition: "Very Good",
    hygieneNote: "Always used with waterproof protector, pet-free and smoke-free home.",
    hasElevator: true,
    deliveryOption: "Pick-up Only",
    description:
      "Used for just under a year in a pet-free, smoke-free apartment. Always protected with a waterproof mattress encasement. Selling because I am relocating internationally and cannot take it with me. The medium feel offers excellent pressure relief. Original receipt available upon request.",
    city: "Hangzhou",
    district: "Xihu District",
    distanceKm: 5.4,
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: true,
    isHygieneVerified: true,
    isCleaned: true,
    wechatId: "tempur_sleep_hz",
    phone: "139-1111-2222",
    createdAt: "2026-06-03",
  },
  {
    id: "ikea-morgedal-hz",
    title: "IKEA MORGEDAL Latex Mattress, Firm",
    brand: "IKEA",
    price: 850,
    retailPrice: 2499,
    size: "1.5m",
    dimensionsText: "1.5m x 2.0m",
    material: "Latex",
    thicknessCm: 18,
    useDuration: "2 years",
    condition: "Excellent",
    hygieneNote: "Machine-washable cover has been freshly laundered. 100% hypoallergenic.",
    hasElevator: false,
    deliveryOption: "Pick-up Only",
    description:
      "Selling a reliable, highly rated IKEA MORGEDAL latex mattress. This is the firm version which is perfect for back support and extremely breathable. Outer cover can be unzipped and machine-washed, making it exceptionally hygienic. Cleaned, stored, and ready to go! Perfect for guests or college students.",
    city: "Hangzhou",
    district: "Gongshu District",
    distanceKm: 8.0,
    images: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: false,
    isHygieneVerified: false,
    isCleaned: true,
    wechatId: "morgedal_ikea",
    phone: "186-0571-0000",
    createdAt: "2026-06-02",
  },
  {
    id: "simmons-black-bj",
    title: "Simmons Beautyrest Black L-Class, King Size",
    brand: "Simmons",
    price: 8500,
    retailPrice: 32000,
    size: "1.8m",
    dimensionsText: "1.8m x 2.0m",
    material: "Spring",
    thicknessCm: 35,
    useDuration: "6 months",
    condition: "Like New",
    hygieneNote: "Always used with full mattress protector, zero stains, dust-mite treated.",
    hasElevator: true,
    deliveryOption: "Pick-up Only",
    description:
      "Ultra-premium Simmons Beautyrest Black. Bought less than half a year ago for 32,000 RMB. Selling due to corporate relocation to Germany. Includes original receipt, pristine condition with Deep Clean certification. Located in a high-end compound with easy elevator freight access.",
    city: "Beijing",
    district: "Chaoyang District",
    distanceKm: 1.5,
    images: [
      "https://images.unsplash.com/photo-1505693395321-883724634266?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: true,
    isHygieneVerified: true,
    isCleaned: true,
    wechatId: "beijing_sim_luxury",
    phone: "135-0000-1111",
    createdAt: "2026-06-04",
  },
  {
    id: "tempur-proadapt-bj",
    title: "Tempur-Pedic ProAdapt Medium, Queen Size",
    brand: "Tempur-Pedic",
    price: 12000,
    retailPrice: 28000,
    size: "1.5m",
    dimensionsText: "1.5m x 2.0m",
    material: "Memory Foam",
    thicknessCm: 30,
    useDuration: "Under 1 Year",
    condition: "Very Good",
    hygieneNote: "Pristine apartment, always fully protected, professional sleep hygiene checked.",
    hasElevator: true,
    deliveryOption: "Pick-up Only",
    description:
      "Selling our beloved Tempur-Pedic ProAdapt Medium Mattress. Exceptionally supportive, pristine memory foam. Purchased at Beijing China World Mall store. Always kept with dual-layer allergy encasements.",
    city: "Beijing",
    district: "Haidian District",
    distanceKm: 4.2,
    images: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: true,
    isHygieneVerified: true,
    isCleaned: true,
    wechatId: "tempur_bj_pro",
    phone: "137-2222-3333",
    createdAt: "2026-06-02",
  },
  {
    id: "serta-perfectlimit-bj",
    title: "Serta Perfect Sleeper Elite, Firm Hybrid",
    brand: "Serta",
    price: 6200,
    retailPrice: 15800,
    size: "1.8m",
    dimensionsText: "1.8m x 2.0m",
    material: "Hybrid",
    thicknessCm: 28,
    useDuration: "8 months",
    condition: "Excellent",
    hygieneNote: "Meticulously cared for, pets outside bedroom, sanitized twice a year.",
    hasElevator: true,
    deliveryOption: "Pick-up Only",
    description:
      "Serta Perfect Sleeper Elite Mattress. This is a top-tier hybrid spring and memory foam mattress that provides traditional support combined with cool comfort layers. Mint condition. Zero sagging. Moving abroad, urgent sale!",
    city: "Beijing",
    district: "Dongcheng District",
    distanceKm: 3.8,
    images: [
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=600&auto=format&fit=crop&q=60",
    ],
    isVerifiedClean: true,
    isHygieneVerified: true,
    isCleaned: true,
    wechatId: "serta_dongcheng",
    phone: "185-1111-5555",
    createdAt: "2026-05-28",
  },
];

export const DEFAULT_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-contact-req",
    type: "contact_request",
    title: "Contact Request / 联络申请",
    timestamp: "刚刚",
    message: "买家 Li Wei 申请复制您的微信 ID，希望与您沟通购买 Simmons Beautyrest Black 床垫的事宜。",
    unread: true,
    actionState: "pending",
    buyerName: "Li Wei",
    listingTitle: "Simmons Beautyrest Black",
  },
  {
    id: "notif-traction",
    type: "insight",
    title: "Listing Traction / 热度反馈",
    timestamp: "2小时前",
    message:
      "您的 Tempur-Pedic ProAdapt 宝贝本周已被加入心愿单 10 次。为了加速成交，建议调低价格以吸引买家目光。",
    unread: false,
    actionState: "pending",
    listingTitle: "Tempur-Pedic ProAdapt",
    listingId: "tempur-proadapt-bj",
  },
  {
    id: "notif-verify",
    type: "verification",
    title: "Verification Complete / 卫检已认证",
    timestamp: "昨天",
    message: "恭喜！您发布的 Hästens Maranga 已经成功通过卫检与除螨认证，带绿色标志发布成功。",
    unread: false,
  },
  {
    id: "notif-trans",
    type: "completed",
    title: "Transaction Completed / 交易完成",
    timestamp: "2023-10-12",
    message: "您出货的 Serta 床垫转让交割已经最终完成。感谢您信任 Restored。",
    unread: false,
  },
];
